# pages/13_Circular_Economy_Optimizer.py

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="Circular Economy Optimizer",
    page_icon="♻️",
    layout="wide"
)

st.title("♻️ AI Circular Economy Optimizer")
st.markdown("""
This AI system evaluates how effectively an organization follows **circular economy principles**:
- Reduce waste
- Reuse materials
- Recycle efficiently
- Extend product lifecycle
""")

# =====================================================
# INPUT SECTION
# =====================================================

st.subheader("📥 Enter Operational Metrics")

col1, col2, col3 = st.columns(3)

with col1:
    material_reuse = st.number_input(
        "Material Reuse Rate (%)",
        min_value=0.0,
        max_value=100.0,
        value=40.0
    )

with col2:
    recycling_rate = st.number_input(
        "Recycling Rate (%)",
        min_value=0.0,
        max_value=100.0,
        value=50.0
    )

with col3:
    waste_generation = st.number_input(
        "Waste Generated (tons)",
        min_value=0.0,
        value=60.0
    )

col4, col5 = st.columns(2)

with col4:
    product_lifetime = st.number_input(
        "Average Product Lifetime (years)",
        min_value=1,
        value=5
    )

with col5:
    circular_design_score = st.number_input(
        "Circular Design Score (0–100)",
        min_value=0.0,
        max_value=100.0,
        value=55.0
    )

# =====================================================
# AI ENGINE
# =====================================================

def calculate_circular_score():

    score = (
        material_reuse * 0.25 +
        recycling_rate * 0.25 +
        circular_design_score * 0.3 +
        (product_lifetime * 5) * 0.1 +
        (100 - waste_generation) * 0.1
    )

    return np.clip(score, 0, 100)

# =====================================================
# BUTTON
# =====================================================

if st.button("♻️ Analyze Circular Economy Performance"):

    score = calculate_circular_score()

    # =====================================================
    # SCORE OUTPUT
    # =====================================================

    st.subheader("📊 Circular Economy Score")

    st.metric("Sustainability Score", f"{score:.2f} / 100")

    if score >= 80:
        st.success("🌟 Excellent Circular Economy Performance")
    elif score >= 60:
        st.info("🟢 Good Circular Practices")
    elif score >= 40:
        st.warning("🟡 Moderate Circular Efficiency")
    else:
        st.error("🔴 Poor Circular Economy Adoption")

    # =====================================================
    # AI INSIGHTS
    # =====================================================

    st.subheader("💡 AI Optimization Insights")

    insights = []

    if material_reuse < 50:
        insights.append("🔄 Increase material reuse to reduce raw material dependency.")

    if recycling_rate < 60:
        insights.append("♻️ Improve recycling infrastructure and sorting efficiency.")

    if waste_generation > 60:
        insights.append("⚠️ High waste generation detected — optimize production processes.")

    if product_lifetime < 5:
        insights.append("⏳ Increase product durability to reduce lifecycle waste.")

    if circular_design_score < 60:
        insights.append("🧠 Improve circular product design strategies.")

    for i in insights:
        st.warning(i)

    if not insights:
        st.success("🎯 Strong circular economy system in place!")

    # =====================================================
    # IMPACT ANALYSIS
    # =====================================================

    st.subheader("🌍 Environmental Impact Overview")

    waste_saved = material_reuse * 0.8 + recycling_rate * 0.6

    st.metric("Estimated Waste Reduction Potential (%)", f"{waste_saved:.2f}")

    # =====================================================
    # REPORT GENERATION
    # =====================================================

    st.subheader("📄 Download Circular Economy Report")

    report = f"""
CIRCULAR ECONOMY ANALYSIS REPORT
Generated: {datetime.now()}

Material Reuse Rate: {material_reuse}%
Recycling Rate: {recycling_rate}%
Waste Generation: {waste_generation} tons
Product Lifetime: {product_lifetime} years
Circular Design Score: {circular_design_score}

Circular Economy Score: {score:.2f}/100
Estimated Waste Reduction Potential: {waste_saved:.2f}%

Generated by AI Circular Economy Optimizer
"""

    st.download_button(
        label="📥 Download Report",
        data=report,
        file_name="circular_economy_report.txt",
        mime="text/plain"
    )

# =====================================================
# FOOTER
# =====================================================

st.markdown("---")
st.caption("♻️ AI ESG Predictive Maintenance | Circular Economy Optimizer Module")
